# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TodoeyiOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoeyiOS13
 pod 'RealmSwift'
 pod "SwipeCellKit"
 pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

  target 'TodoeyiOS13Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
